### ISSUE TITLE
[BUG] Deprecated imports in ovos-utils 0.1.0

### ISSUE THREAD

**Issue by mikejgray** [NeonGeckoCom/neon_audio#170]
### Description

```
❯ neon-audio run
2024-04-25 23:32:27.402 - neon-utils - neon_utils.configuration_utils:get_config_dir - WARNING - Deprecation version=2.0.0. Caller=neon_audio.cli:59. Use `ovos_config.locations.get_xdg_config_save_path` directly
2024-04-25 23:32:27.405 - neon-utils - neon_utils.configuration_utils:_validate_config_env:535 - INFO - NEON_CONFIG_PATH=/Users/Mike/.config/neon
2024-04-25 23:32:27.405 - neon-utils - neon_utils.configuration_utils:_validate_config_env:539 - WARNING - NEON_CONFIG_PATH set, updating XDG_CONFIG_HOME to /Users/Mike/.config
2024-04-25 23:32:27.406 - neon-utils - neon_utils.packaging_utils:get_neon_core_root - WARNING - Deprecation version=2.0.0. Caller=neon_utils.configuration_utils:473. Use system modules to locate packages and resources
2024-04-25 23:32:28.237 - neon-utils - neon_utils.configuration_utils:_init_ovos_conf:512 - ERROR - Failed to override mycroft.configuration: cannot import name 'play_acknowledge_sound' from 'ovos_utils.sound' (/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/ovos_utils/sound.py)
Traceback (most recent call last):
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/bin/neon-audio", line 8, in <module>
    sys.exit(neon_audio_cli())
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/neon_audio/cli.py", line 60, in run
    from neon_audio.__main__ import main
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/neon_audio/__main__.py", line 39, in <module>
    from neon_audio.service import NeonPlaybackService
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/neon_audio/service.py", line 35, in <module>
    from neon_audio.tts import TTSFactory
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/neon_audio/tts/__init__.py", line 34, in <module>
    from neon_audio.tts.neon import TTS, WrappedTTS
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/neon_audio/tts/neon.py", line 41, in <module>
    from ovos_utils.enclosure.api import EnclosureAPI
ModuleNotFoundError: No module named 'ovos_utils.enclosure'
```

A number of imports have been deprecated in ovos-utils 0.1.0, both with and without replacement, and need to be resolved before Neon will work with that codebase.

**Comment by NeonDaniel** [comment]
#169 #171 and #172 contribute to this

**Comment by NeonDaniel** [comment]
No deprecated imports remaining
